#!/bin/bash

##
# u_ping stands for "Universal Ping". Auxiliar funcition. It must checks if the ping present in the system is the Linux ping or Microsoft ping to choose the right parameter to provides
uping() {

    if [ ${#1} -eq 0 ]; then
        echo You must provides the site to ping.
        return
    fi

    ping_source=$(which ping)
    site_to_ping=$1

    # Tests if exists Windows/system32 in the path. If so, is the Windows ping utility.
    shopt -s nocasematch
    if [[ $ping_source =~ 'windows/system32' ]]; then
        ping -n 2 $site_to_ping > /dev/null
    else
        ping -c 2 $site_to_ping > /dev/null
    fi
}

uping $1