#!/bin/bash

if [ -z $1 ]; then
	echo $0 error: You must provides the first argument to be the folder to have its scripts loaded
	return
fi

if ! [ -d $1 ]; then
	echo $0 error: The provided path does not exists
	return
fi

for i in `ls $1 | grep -Ev "~$"`; do
	source $1/$i
done
